retail360:
  outputs:
    dev:
      account: YGPBDMF-WEB14858
      database: RETAIL360
      password: Snowflake@1234
      role: ACCOUNTADMIN
      schema: STAGING
      threads: 2
      type: snowflake
      user: AVIRALSINGH24
      warehouse: COMPUTE_WH
  target: dev
