retail360:
  outputs:
    dev:
      account: {{ env_var('SNOWFLAKE_ACCOUNT')}}
      database: RETAIL360
      password: {{ env_var('SNOWFLAKE_PASSWORD')}}
      role: ACCOUNTADMIN
      schema: STAGING
      threads: 2
      type: snowflake
      user: {{ env_var('SNOWFLAKE_USER')}}
      warehouse: COMPUTE_WH
  target: dev
